### PR TITLE
day1 IO part + troubleshooting presentation

### PR DESCRIPTION
**Pull request by thempel**
I'm happy about comments, suggestions or improvements of any kind!

### CODE REVIEW

**Comment by marscher** [comment]
just started reading... looks good so far. Please import pyemma.util.contexts on top or directly import the settings function to avoid trouble.

**Comment by marscher** [comment]
in nb0, do you really want only every 75th frame to be considered during clustering or is that a debug setting?

**Comment by thempel** [comment]
Thanks for reviewing! I've imported `pyemma.util.contexts` or the function directly.

> in nb0, do you really want only every 75th frame to be considered during clustering or is that a debug setting? 

It's enough to reproduce the usual results here. Since I don't know how fast that macbook is that I have to use during the presentation, I thought I'd better push this as far as possible. As it's only in the presentation notebook, I will mention that it's a pretty high number so people hopefully don't adopt it.

**Comment by marscher** [comment]
On 2/15/19 6:07 PM, Tim Hempel wrote:
> Thanks for reviewing! I've imported |pyemma.util.contexts| or the 
> function directly.
> 
>     in nb0, do you really want only every 75th frame to be considered
>     during clustering or is that a debug setting?
> 
> It's enough to reproduce the usual results here. Since I don't know how 
> fast that macbook is that I have to use during the presentation, I 
> thought I'd better push this as far as possible. As it's only in the 
> presentation notebook, I will mention that it's a pretty high number so 
> people hopefully don't adopt it.
If we get a sane result, that's fine, but I'd guess you should give the 
users a hint, that 75 is not a real world value.

**Comment by thempel** [comment]
If you insist ;-) I've added an in-line comment.

**Comment by marscher** [comment]
Thank you!

**Pull request merged**
